strain_id_field: "accession"
# root: "A/Sample/2009"

subsampling:
  all: --min-length '9800' --query "country == 'USA' & accession != 'NC_009942'"

# subsampling:
#   state: --query "division == 'WA'"
#   neighboring_state: --query "division in ['ID', 'OR']" --group-by division year --subsample-max-sequences 200
#   country: --query "country == 'USA' and division not in ['WA', 'ID', 'OR']" --group-by division year --subsample-max-sequences 200
#   global: --query "country != 'USA'" --group-by country year --subsample-max-sequences 200